from __future__ import annotations

from typing import TypedDict


class CatalogEntry(TypedDict, total=False):
    id: str
    name: str
    url: str
    source_type: str
    category: str
    description: str
    trust_score: float
    polling_interval_minutes: int
    fetch_full_text: bool


CATALOG: list[CatalogEntry] = [
    # ── AI ──────────────────────────────────────────────────────────────────
    {
        "id": "import-ai-openai-blog",
        "name": "OpenAI Blog",
        "url": "https://openai.com/blog/rss.xml",
        "source_type": "rss",
        "category": "ai",
        "description": "Official OpenAI research and product announcements",
        "trust_score": 0.9,
        "polling_interval_minutes": 60,
        "fetch_full_text": True,
    },
    {
        "id": "import-ai-huggingface",
        "name": "Hugging Face Blog",
        "url": "https://huggingface.co/blog/feed.xml",
        "source_type": "rss",
        "category": "ai",
        "description": "Open-source AI models, papers, and tooling updates",
        "trust_score": 0.85,
        "polling_interval_minutes": 60,
    },
    {
        "id": "import-ai-the-decoder",
        "name": "The Decoder",
        "url": "https://the-decoder.com/feed/",
        "source_type": "rss",
        "category": "ai",
        "description": "In-depth AI news and research coverage",
        "trust_score": 0.8,
        "polling_interval_minutes": 60,
    },
    {
        "id": "import-ai-mit-news",
        "name": "MIT News – AI",
        "url": "https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml",
        "source_type": "rss",
        "category": "ai",
        "description": "MIT research on artificial intelligence",
        "trust_score": 0.9,
        "polling_interval_minutes": 120,
    },
    {
        "id": "import-ai-deepmind-blog",
        "name": "Google DeepMind Blog",
        "url": "https://deepmind.google/blog/rss.xml",
        "source_type": "rss",
        "category": "ai",
        "description": "DeepMind research updates and breakthroughs",
        "trust_score": 0.9,
        "polling_interval_minutes": 120,
    },
    # ── TECHNOLOGY ───────────────────────────────────────────────────────────
    {
        "id": "import-tech-techcrunch",
        "name": "TechCrunch",
        "url": "https://techcrunch.com/feed/",
        "source_type": "rss",
        "category": "technology",
        "description": "Startup and technology news",
        "trust_score": 0.8,
        "polling_interval_minutes": 30,
    },
    {
        "id": "import-tech-arstechnica",
        "name": "Ars Technica",
        "url": "https://feeds.arstechnica.com/arstechnica/index",
        "source_type": "rss",
        "category": "technology",
        "description": "In-depth technology, science, and culture",
        "trust_score": 0.85,
        "polling_interval_minutes": 30,
    },
    {
        "id": "import-tech-theverge",
        "name": "The Verge",
        "url": "https://www.theverge.com/rss/index.xml",
        "source_type": "rss",
        "category": "technology",
        "description": "Technology news, product reviews, and culture",
        "trust_score": 0.8,
        "polling_interval_minutes": 30,
    },
    {
        "id": "import-tech-wired",
        "name": "WIRED",
        "url": "https://www.wired.com/feed/rss",
        "source_type": "rss",
        "category": "technology",
        "description": "Technology, science, culture, and business",
        "trust_score": 0.8,
        "polling_interval_minutes": 60,
    },
    {
        "id": "import-tech-hackernews",
        "name": "Hacker News (Top)",
        "url": "https://hnrss.org/frontpage",
        "source_type": "rss",
        "category": "technology",
        "description": "Community-curated tech and startup links",
        "trust_score": 0.75,
        "polling_interval_minutes": 15,
    },
    # ── POLITICS ─────────────────────────────────────────────────────────────
    {
        "id": "import-politics-reuters",
        "name": "Reuters – Politics",
        "url": "https://feeds.reuters.com/reuters/politicsNews",
        "source_type": "rss",
        "category": "politics",
        "description": "Reuters wire politics coverage",
        "trust_score": 0.9,
        "polling_interval_minutes": 15,
    },
    {
        "id": "import-politics-ap",
        "name": "AP News – Politics",
        "url": "https://feeds.apnews.com/apf-politics",
        "source_type": "rss",
        "category": "politics",
        "description": "Associated Press political reporting",
        "trust_score": 0.9,
        "polling_interval_minutes": 15,
    },
    {
        "id": "import-politics-bbc-world",
        "name": "BBC News – World",
        "url": "https://feeds.bbci.co.uk/news/world/rss.xml",
        "source_type": "rss",
        "category": "politics",
        "description": "BBC international news and politics",
        "trust_score": 0.9,
        "polling_interval_minutes": 15,
    },
    {
        "id": "import-politics-guardian",
        "name": "The Guardian – World",
        "url": "https://www.theguardian.com/world/rss",
        "source_type": "rss",
        "category": "politics",
        "description": "Guardian international reporting",
        "trust_score": 0.85,
        "polling_interval_minutes": 30,
    },
    # ── GAMING ───────────────────────────────────────────────────────────────
    {
        "id": "import-gaming-ign",
        "name": "IGN",
        "url": "https://feeds.ign.com/ign/all",
        "source_type": "rss",
        "category": "gaming",
        "description": "Games, movies, and entertainment news",
        "trust_score": 0.75,
        "polling_interval_minutes": 30,
    },
    {
        "id": "import-gaming-kotaku",
        "name": "Kotaku",
        "url": "https://kotaku.com/rss",
        "source_type": "rss",
        "category": "gaming",
        "description": "Gaming news, reviews, and culture",
        "trust_score": 0.75,
        "polling_interval_minutes": 30,
    },
    {
        "id": "import-gaming-rps",
        "name": "Rock Paper Shotgun",
        "url": "https://www.rockpapershotgun.com/feed",
        "source_type": "rss",
        "category": "gaming",
        "description": "PC gaming news and reviews",
        "trust_score": 0.75,
        "polling_interval_minutes": 30,
    },
    {
        "id": "import-gaming-eurogamer",
        "name": "Eurogamer",
        "url": "https://www.eurogamer.net/?format=rss",
        "source_type": "rss",
        "category": "gaming",
        "description": "European gaming news and reviews",
        "trust_score": 0.75,
        "polling_interval_minutes": 30,
    },
    # ── SCIENCE ──────────────────────────────────────────────────────────────
    {
        "id": "import-science-nature",
        "name": "Nature – News",
        "url": "https://www.nature.com/nature.rss",
        "source_type": "rss",
        "category": "science",
        "description": "Leading scientific journal news",
        "trust_score": 0.95,
        "polling_interval_minutes": 120,
    },
    {
        "id": "import-science-newscientist",
        "name": "New Scientist",
        "url": "https://www.newscientist.com/feed/home/",
        "source_type": "rss",
        "category": "science",
        "description": "Science and technology news for a general audience",
        "trust_score": 0.85,
        "polling_interval_minutes": 60,
    },
    {
        "id": "import-science-nasa",
        "name": "NASA Breaking News",
        "url": "https://www.nasa.gov/rss/dyn/breaking_news.rss",
        "source_type": "rss",
        "category": "science",
        "description": "NASA space and science announcements",
        "trust_score": 0.95,
        "polling_interval_minutes": 60,
    },
    # ── BUSINESS ─────────────────────────────────────────────────────────────
    {
        "id": "import-business-reuters-finance",
        "name": "Reuters – Finance",
        "url": "https://feeds.reuters.com/reuters/businessNews",
        "source_type": "rss",
        "category": "business",
        "description": "Reuters business and financial wire",
        "trust_score": 0.9,
        "polling_interval_minutes": 15,
    },
    {
        "id": "import-business-ft",
        "name": "Financial Times",
        "url": "https://www.ft.com/rss/home",
        "source_type": "rss",
        "category": "business",
        "description": "Global financial and business news",
        "trust_score": 0.9,
        "polling_interval_minutes": 30,
    },
    {
        "id": "import-business-wsj",
        "name": "Wall Street Journal",
        "url": "https://feeds.wsj.com/wsj/xml/rss/3_7031.xml",
        "source_type": "rss",
        "category": "business",
        "description": "WSJ markets and business news",
        "trust_score": 0.9,
        "polling_interval_minutes": 30,
    },
    # ── CRYPTO ───────────────────────────────────────────────────────────────
    {
        "id": "import-crypto-coindesk",
        "name": "CoinDesk",
        "url": "https://www.coindesk.com/arc/outboundfeeds/rss/",
        "source_type": "rss",
        "category": "crypto",
        "description": "Cryptocurrency and blockchain news",
        "trust_score": 0.75,
        "polling_interval_minutes": 30,
    },
    {
        "id": "import-crypto-cointelegraph",
        "name": "Cointelegraph",
        "url": "https://cointelegraph.com/rss",
        "source_type": "rss",
        "category": "crypto",
        "description": "Crypto markets, DeFi, and Web3 news",
        "trust_score": 0.7,
        "polling_interval_minutes": 30,
    },
    # ── HEALTH ───────────────────────────────────────────────────────────────
    {
        "id": "import-health-who",
        "name": "WHO – News",
        "url": "https://www.who.int/rss-feeds/news-english.xml",
        "source_type": "rss",
        "category": "health",
        "description": "World Health Organization official updates",
        "trust_score": 0.95,
        "polling_interval_minutes": 120,
    },
    {
        "id": "import-health-statnews",
        "name": "STAT News",
        "url": "https://www.statnews.com/feed/",
        "source_type": "rss",
        "category": "health",
        "description": "Health, medicine, and life sciences reporting",
        "trust_score": 0.85,
        "polling_interval_minutes": 60,
    },
]

CATALOG_BY_ID: dict[str, CatalogEntry] = {entry["id"]: entry for entry in CATALOG}

CATALOG_CATEGORIES: list[str] = sorted({entry["category"] for entry in CATALOG})
