/**
 * Phase 8 — Backend ↔ frontend feature parity inventory.
 * Every active OpenAPI operation is classified exactly once.
 * USER_FACING_UI requires client + ui; other categories require exemptionReason.
 */
import type { ParityOperation } from "./parityTypes";

export const PARITY_OPERATIONS: readonly ParityOperation[] = [
  { method: "GET", path: "/api/v1/analytics/overview", category: "USER_FACING_UI", client: "api/analytics.ts#getAnalyticsOverview", ui: "pages/AnalyticsPage.tsx" },
  { method: "POST", path: "/api/v1/analytics/sync", category: "USER_FACING_UI", client: "api/analytics.ts#syncAnalytics", ui: "pages/AnalyticsPage.tsx" },
  { method: "GET", path: "/api/v1/approvals", category: "USER_FACING_UI", client: "api/approvals.ts#getApprovalRequests", ui: "pages/ApprovalsPage.tsx" },
  { method: "POST", path: "/api/v1/approvals", category: "USER_FACING_UI", client: "api/approvals.ts#sendApprovalRequest", ui: "pages/ApprovalsPage.tsx" },
  { method: "POST", path: "/api/v1/approvals/telegram/webhook", category: "WEBHOOK", exemptionReason: "Inbound Telegram approval callback; no product UI." },
  { method: "GET", path: "/api/v1/approvals/whatsapp/webhook", category: "WEBHOOK", exemptionReason: "Inbound WhatsApp verification/callback; no product UI." },
  { method: "POST", path: "/api/v1/approvals/whatsapp/webhook", category: "WEBHOOK", exemptionReason: "Inbound WhatsApp approval callback; no product UI." },
  { method: "POST", path: "/api/v1/workflows/webhooks/{endpoint_id}", category: "WEBHOOK", exemptionReason: "Inbound signed automation webhook/event trigger; no product UI." },
  { method: "GET", path: "/api/v1/approvals/{request_id}", category: "INTENTIONALLY_NO_UI", exemptionReason: "List endpoint powers ApprovalsPage; single-id fetch reserved for future deep links." },
  { method: "POST", path: "/api/v1/approvals/{request_id}/action", category: "USER_FACING_UI", client: "api/approvals.ts#actionApprovalRequest", ui: "pages/ApprovalsPage.tsx" },
  { method: "POST", path: "/api/v1/approvals/{request_id}/resend", category: "USER_FACING_UI", client: "api/approvals.ts#resendApprovalRequest", ui: "pages/ApprovalsPage.tsx" },
  { method: "GET", path: "/api/v1/audit/logs", category: "USER_FACING_UI", client: "api/settings.ts#getAuditLogs", ui: "pages/AuditPage.tsx" },
  { method: "POST", path: "/api/v1/auth/forgot-password", category: "USER_FACING_UI", client: "api/auth.ts#forgotPassword", ui: "pages/AuthHomePage.tsx" },
  { method: "POST", path: "/api/v1/auth/logout", category: "USER_FACING_UI", client: "api/auth.ts#logout", ui: "features/auth/AuthContext.tsx" },
  { method: "GET", path: "/api/v1/auth/me", category: "USER_FACING_UI", client: "api/auth.ts#me", ui: "features/auth/AuthContext.tsx" },
  { method: "POST", path: "/api/v1/auth/mfa/disable", category: "USER_FACING_UI", client: "api/auth.ts#disableMfa", ui: "features/settings/AccountTab.tsx" },
  { method: "POST", path: "/api/v1/auth/mfa/enable", category: "USER_FACING_UI", client: "api/auth.ts#enableMfa", ui: "pages/MfaSetupPage.tsx" },
  { method: "POST", path: "/api/v1/auth/mfa/verify", category: "USER_FACING_UI", client: "api/auth.ts#verifyMfa", ui: "pages/MfaSetupPage.tsx" },
  { method: "POST", path: "/api/v1/auth/refresh", category: "FRONTEND_INTERNAL", client: "api/auth.ts#refresh", ui: "features/auth/AuthContext.tsx", exemptionReason: "Session bootstrap/refresh; not a standalone page action." },
  { method: "POST", path: "/api/v1/auth/resend-verification", category: "USER_FACING_UI", client: "api/auth.ts#resendVerification", ui: "pages/VerifyEmailPage.tsx" },
  { method: "POST", path: "/api/v1/auth/reset-password", category: "USER_FACING_UI", client: "api/auth.ts#resetPassword", ui: "pages/ResetPasswordPage.tsx" },
  { method: "POST", path: "/api/v1/auth/sign-in", category: "USER_FACING_UI", client: "api/auth.ts#signIn", ui: "features/auth/AuthContext.tsx" },
  { method: "POST", path: "/api/v1/auth/sign-up", category: "USER_FACING_UI", client: "api/auth.ts#signUp", ui: "features/auth/AuthContext.tsx" },
  { method: "POST", path: "/api/v1/auth/verify-email", category: "USER_FACING_UI", client: "api/auth.ts#verifyEmail", ui: "pages/VerifyEmailPage.tsx" },
  { method: "POST", path: "/api/v1/briefs", category: "USER_FACING_UI", client: "api/briefs.ts#generateBrief", ui: "pages/EditorialBriefsPage.tsx" },
  { method: "GET", path: "/api/v1/briefs", category: "USER_FACING_UI", client: "api/briefs.ts#getBriefs", ui: "pages/EditorialBriefsPage.tsx" },
  { method: "GET", path: "/api/v1/briefs/{brief_id}", category: "INTENTIONALLY_NO_UI", exemptionReason: "Briefs list powers EditorialBriefsPage; single-brief fetch reserved for future deep links." },
  { method: "POST", path: "/api/v1/briefs/{brief_id}/approve", category: "USER_FACING_UI", client: "api/briefs.ts#approveBrief", ui: "pages/EditorialBriefsPage.tsx" },
  { method: "POST", path: "/api/v1/briefs/{brief_id}/regenerate", category: "USER_FACING_UI", client: "api/briefs.ts#regenerateBrief", ui: "pages/EditorialBriefsPage.tsx" },
  { method: "POST", path: "/api/v1/briefs/{brief_id}/reject", category: "USER_FACING_UI", client: "api/briefs.ts#rejectBrief", ui: "pages/EditorialBriefsPage.tsx" },
  { method: "POST", path: "/api/v1/briefs/{brief_id}/rewrite", category: "USER_FACING_UI", client: "api/briefs.ts#rewriteBrief", ui: "pages/EditorialBriefsPage.tsx" },
  { method: "POST", path: "/api/v1/briefs/{brief_id}/send-telegram", category: "USER_FACING_UI", client: "api/briefs.ts#sendBriefToTelegram", ui: "pages/EditorialBriefsPage.tsx" },
  { method: "POST", path: "/api/v1/chess-videos/validate", category: "USER_FACING_UI", client: "api/chessVideos.ts#validateChessGame", ui: "pages/ChessVideoPage.tsx" },
  { method: "POST", path: "/api/v1/chess-videos", category: "USER_FACING_UI", client: "api/chessVideos.ts#createChessVideo", ui: "pages/ChessVideoPage.tsx" },
  { method: "GET", path: "/api/v1/chess-videos", category: "USER_FACING_UI", client: "api/chessVideos.ts#getChessVideoJobs", ui: "pages/ChessVideoPage.tsx" },
  { method: "GET", path: "/api/v1/chess-videos/{job_id}", category: "USER_FACING_UI", client: "api/chessVideos.ts#getChessVideoJob", ui: "pages/ChessVideoPage.tsx" },
  { method: "POST", path: "/api/v1/chess-videos/{job_id}/retry", category: "USER_FACING_UI", client: "api/chessVideos.ts#retryChessVideoJob", ui: "pages/ChessVideoPage.tsx" },
  { method: "DELETE", path: "/api/v1/chess-videos/{job_id}", category: "USER_FACING_UI", client: "api/chessVideos.ts#deleteChessVideoJob", ui: "pages/ChessVideoPage.tsx" },
  { method: "POST", path: "/api/v1/chess/games/{game_id}/video", category: "USER_FACING_UI", client: "api/chessData.ts#createChessVideoFromGame", ui: "features/chess" },
  { method: "POST", path: "/api/v1/chess/games/{game_id}/analyze", category: "USER_FACING_UI", client: "api/chessData.ts#enqueueChessGameAnalysis", ui: "features/chess/AnalyzeGameAction.tsx" },
  { method: "GET", path: "/api/v1/chess/games/{game_id}/analysis", category: "USER_FACING_UI", client: "api/chessData.ts#getChessGameAnalysis", ui: "features/chess/AnalyzeGameAction.tsx" },
  { method: "GET", path: "/api/v1/chess/analysis/{job_id}", category: "USER_FACING_UI", client: "api/chessData.ts#getChessAnalysisJob", ui: "features/chess/AnalyzeGameAction.tsx" },
  { method: "GET", path: "/api/v1/chess/games/{game_id}/content-score", category: "USER_FACING_UI", client: "api/chessData.ts#getChessGameContentScore", ui: "features/chess/ContentOpportunityPanel.tsx" },
  { method: "GET", path: "/api/v1/chess/games/{game_id}/provenance", category: "USER_FACING_UI", client: "api/chessData.ts#getChessGameProvenance", ui: "features/chess/ProvenancePanel.tsx" },
  { method: "GET", path: "/api/v1/chess/puzzles/{puzzle_id}/provenance", category: "USER_FACING_UI", client: "api/chessData.ts#getChessPuzzleProvenance", ui: "features/chess" },
  { method: "GET", path: "/api/v1/chess-videos/{job_id}/provenance", category: "USER_FACING_UI", client: "api/chessVideos.ts#getChessVideoProvenance", ui: "features/chess" },
  { method: "GET", path: "/api/v1/chess/games", category: "USER_FACING_UI", client: "api/chessData.ts#searchChessGames", ui: "features/chess" },
  { method: "GET", path: "/api/v1/chess/games/famous", category: "USER_FACING_UI", client: "api/chessData.ts#listFamousChessGames", ui: "features/chess" },
  { method: "GET", path: "/api/v1/chess/puzzles", category: "USER_FACING_UI", client: "api/chessData.ts#searchChessPuzzles", ui: "features/chess" },
  { method: "GET", path: "/api/v1/chess/puzzles/daily", category: "USER_FACING_UI", client: "api/chessData.ts#getDailyChessPuzzle", ui: "features/chess" },
  { method: "POST", path: "/api/v1/content/asset-groups/{asset_group_id}/regenerate", category: "USER_FACING_UI", client: "api/content.ts#regenerateAssetGroup", ui: "pages/ContentDetailPage.tsx" },
  { method: "GET", path: "/api/v1/content/brand-profile", category: "USER_FACING_UI", client: "api/content.ts#getBrandProfile", ui: "pages/BrandProfilePage.tsx" },
  { method: "PUT", path: "/api/v1/content/brand-profile", category: "USER_FACING_UI", client: "api/content.ts#upsertBrandProfile", ui: "pages/BrandProfilePage.tsx" },
  { method: "POST", path: "/api/v1/content/generate", category: "USER_FACING_UI", client: "api/content.ts#generateContent", ui: "features/content/PlansTab.tsx" },
  { method: "GET", path: "/api/v1/content/jobs", category: "USER_FACING_UI", client: "api/content.ts#getContentJobs", ui: "features/content/PlansTab.tsx" },
  { method: "GET", path: "/api/v1/content/jobs/{job_id}", category: "USER_FACING_UI", client: "api/content.ts#getContentJob", ui: "pages/ContentDetailPage.tsx" },
  { method: "POST", path: "/api/v1/content/jobs/{job_id}/regenerate", category: "USER_FACING_UI", client: "api/content.ts#regenerateContent", ui: "pages/ContentDetailPage.tsx" },
  { method: "GET", path: "/api/v1/content/plans", category: "USER_FACING_UI", client: "api/content.ts#getContentPlans", ui: "features/content/PlansTab.tsx" },
  { method: "POST", path: "/api/v1/content/plans", category: "USER_FACING_UI", client: "api/content.ts#createContentPlan", ui: "features/content/PlansTab.tsx" },
  { method: "GET", path: "/api/v1/content/plans/{plan_id}", category: "INTENTIONALLY_NO_UI", exemptionReason: "Plans list powers Content UI; single-plan fetch reserved for future deep links." },
  { method: "GET", path: "/api/v1/health/config", category: "FRONTEND_INTERNAL", client: "api/health.ts#getAppConfig", ui: "pages/AuthHomePage.tsx", exemptionReason: "Public bootstrap config for auth/MFA gating." },
  { method: "GET", path: "/api/v1/health/live", category: "HEALTH_OBSERVABILITY", exemptionReason: "Liveness probe for orchestrators; not a product surface." },
  { method: "GET", path: "/api/v1/health/metrics", category: "HEALTH_OBSERVABILITY", exemptionReason: "Prometheus/ops metrics scrape; not a product surface." },
  { method: "GET", path: "/api/v1/health/ready", category: "USER_FACING_UI", client: "api/health.ts#getHealthReadiness", ui: "pages/DashboardPage.tsx" },
  { method: "GET", path: "/api/v1/health/version", category: "HEALTH_OBSERVABILITY", exemptionReason: "Deploy version probe; not a product surface." },
  { method: "POST", path: "/api/v1/health/web-vitals", category: "FRONTEND_INTERNAL", client: "telemetry/webVitals.ts#initWebVitals", exemptionReason: "Anonymous RUM beacon; no operator UI." },
  { method: "GET", path: "/api/v1/publishing/connected-accounts", category: "USER_FACING_UI", client: "api/publishing.ts#getConnectedAccounts", ui: "pages/ConnectedAccountsPage.tsx" },
  { method: "POST", path: "/api/v1/publishing/connected-accounts/{connected_account_id}/validate", category: "USER_FACING_UI", client: "api/publishing.ts#validateConnectedAccount", ui: "pages/ConnectedAccountsPage.tsx" },
  { method: "GET", path: "/api/v1/publishing/posts", category: "USER_FACING_UI", client: "api/publishing.ts#getPublishedPosts", ui: "pages/PublishingQueuePage.tsx" },
  { method: "POST", path: "/api/v1/publishing/publish-now", category: "USER_FACING_UI", client: "api/publishing.ts#publishNow", ui: "features/content/PublishingTab.tsx" },
  { method: "GET", path: "/api/v1/publishing/queue", category: "USER_FACING_UI", client: "api/publishing.ts#getPublishingJobs", ui: "pages/PublishingQueuePage.tsx" },
  { method: "POST", path: "/api/v1/publishing/queue/{job_id}/cancel", category: "USER_FACING_UI", client: "api/publishing.ts#cancelPublishingJob", ui: "pages/PublishingQueuePage.tsx" },
  { method: "POST", path: "/api/v1/publishing/queue/{job_id}/retry", category: "USER_FACING_UI", client: "api/publishing.ts#retryPublishingJob", ui: "pages/PublishingQueuePage.tsx" },
  { method: "GET", path: "/api/v1/publishing/social-accounts", category: "USER_FACING_UI", client: "api/publishing.ts#getSocialAccounts", ui: "pages/ConnectedAccountsPage.tsx" },
  { method: "POST", path: "/api/v1/publishing/social-accounts", category: "USER_FACING_UI", client: "api/publishing.ts#upsertSocialAccount", ui: "pages/SettingsPage.tsx" },
  { method: "GET", path: "/api/v1/settings/telegram", category: "USER_FACING_UI", client: "api/settings.ts#getTelegramSettings", ui: "pages/SettingsPage.tsx" },
  { method: "PUT", path: "/api/v1/settings/telegram", category: "USER_FACING_UI", client: "api/settings.ts#updateTelegramSettings", ui: "pages/SettingsPage.tsx" },
  { method: "POST", path: "/api/v1/settings/telegram/register-webhook", category: "USER_FACING_UI", client: "api/settings.ts#registerTelegramWebhook", ui: "pages/SettingsPage.tsx" },
  { method: "POST", path: "/api/v1/settings/telegram/send-daily-digest-test", category: "USER_FACING_UI", client: "api/settings.ts#sendTelegramDailyDigestTest", ui: "pages/SettingsPage.tsx" },
  { method: "GET", path: "/api/v1/settings/tenant", category: "USER_FACING_UI", client: "api/settings.ts#getTenantSettings", ui: "pages/SettingsPage.tsx" },
  { method: "PUT", path: "/api/v1/settings/tenant", category: "USER_FACING_UI", client: "api/settings.ts#updateTenantSettings", ui: "pages/SettingsPage.tsx" },
  { method: "GET", path: "/api/v1/settings/whatsapp", category: "USER_FACING_UI", client: "api/settings.ts#getWhatsAppSettings", ui: "pages/SettingsPage.tsx" },
  { method: "PUT", path: "/api/v1/settings/whatsapp", category: "USER_FACING_UI", client: "api/settings.ts#updateWhatsAppSettings", ui: "pages/SettingsPage.tsx" },
  { method: "GET", path: "/api/v1/sources", category: "USER_FACING_UI", client: "api/sources.ts#getSources", ui: "features/sources/useSourcesQueries.ts" },
  { method: "POST", path: "/api/v1/sources", category: "USER_FACING_UI", client: "api/sources.ts#createSource", ui: "features/sources/useSourcesMutations.ts" },
  { method: "GET", path: "/api/v1/sources/articles", category: "USER_FACING_UI", client: "api/sources.ts#getRawArticles", ui: "features/sources/useSourcesQueries.ts" },
  { method: "GET", path: "/api/v1/sources/catalog", category: "USER_FACING_UI", client: "api/sources.ts#getCatalog", ui: "features/sources/components.tsx" },
  { method: "POST", path: "/api/v1/sources/catalog/{catalog_id}/import", category: "USER_FACING_UI", client: "api/sources.ts#importCatalogSource", ui: "features/sources/useSourcesMutations.ts" },
  { method: "GET", path: "/api/v1/sources/fetch-runs", category: "USER_FACING_UI", client: "api/sources.ts#getSourceFetchRuns", ui: "features/sources/FetchRunsPanel.tsx" },
  { method: "GET", path: "/api/v1/sources/fetch-runs/{fetch_run_id}", category: "USER_FACING_UI", client: "api/sources.ts#getSourceFetchRun", ui: "features/sources/FetchRunsPanel.tsx" },
  { method: "GET", path: "/api/v1/sources/health", category: "USER_FACING_UI", client: "api/sources.ts#getSourceHealth", ui: "features/sources/useSourcesQueries.ts" },
  { method: "PATCH", path: "/api/v1/sources/{source_id}", category: "USER_FACING_UI", client: "api/sources.ts#updateSource", ui: "features/sources/useSourcesMutations.ts" },
  { method: "DELETE", path: "/api/v1/sources/{source_id}", category: "USER_FACING_UI", client: "api/sources.ts#deleteSource", ui: "features/sources/useSourcesMutations.ts" },
  { method: "POST", path: "/api/v1/sources/{source_id}/disable", category: "USER_FACING_UI", client: "api/sources.ts#disableSource", ui: "features/sources/useSourcesMutations.ts" },
  { method: "POST", path: "/api/v1/sources/{source_id}/ingest", category: "USER_FACING_UI", client: "api/sources.ts#triggerIngestion", ui: "features/sources/useSourcesMutations.ts" },
  { method: "POST", path: "/api/v1/sources/{source_id}/manual-poll", category: "USER_FACING_UI", client: "api/sources.ts#triggerManualPoll", ui: "features/sources/useSourcesMutations.ts" },
  { method: "GET", path: "/api/v1/stories/candidates", category: "USER_FACING_UI", client: "api/stories.ts#getTrendCandidates", ui: "pages/StoryDetailPage.tsx" },
  { method: "GET", path: "/api/v1/stories/candidates/{candidate_id}", category: "USER_FACING_UI", client: "api/stories.ts#getTrendCandidate", ui: "pages/StoryDetailPage.tsx" },
  { method: "POST", path: "/api/v1/stories/candidates/{candidate_id}/action", category: "USER_FACING_UI", client: "api/stories.ts#actionTrendCandidate", ui: "pages/StoryDetailPage.tsx" },
  { method: "GET", path: "/api/v1/stories/clusters", category: "USER_FACING_UI", client: "api/stories.ts#getStoryClusters", ui: "pages/StoriesPage.tsx" },
  { method: "GET", path: "/api/v1/stories/clusters/{cluster_id}", category: "USER_FACING_UI", client: "api/stories.ts#getStoryCluster", ui: "pages/StoryDetailPage.tsx" },
  { method: "GET", path: "/api/v1/stories/trends/dashboard", category: "USER_FACING_UI", client: "api/stories.ts#getTrendDashboard", ui: "pages/DashboardPage.tsx" },
  { method: "GET", path: "/api/v1/trending-repos", category: "USER_FACING_UI", client: "api/trending.ts#getTrendingRepos", ui: "pages/TrendingReposPage.tsx" },
  { method: "POST", path: "/api/v1/trending-repos/refresh", category: "USER_FACING_UI", client: "api/trending.ts#refreshTrendingRepos", ui: "pages/TrendingReposPage.tsx" },
  { method: "POST", path: "/api/v1/trending-repos/send-digest", category: "USER_FACING_UI", client: "api/trending.ts#sendTelegramDigest", ui: "pages/TrendingReposPage.tsx" },
  { method: "POST", path: "/api/v1/trending-repos/{repo_id}/generate-ideas", category: "USER_FACING_UI", client: "api/trending.ts#generateProductIdeas", ui: "features/trending/RepoCard.tsx" },
  { method: "POST", path: "/api/v1/trending-repos/{repo_id}/generate-twitter-post", category: "USER_FACING_UI", client: "api/trending.ts#generateTwitterPost", ui: "features/trending/RepoCard.tsx" },
  { method: "POST", path: "/api/v1/trending-repos/{repo_id}/post-to-twitter", category: "USER_FACING_UI", client: "api/trending.ts#postToTwitter", ui: "features/trending/TwitterPostCard.tsx" },
  { method: "PUT", path: "/api/v1/workflows/definitions/{definition_id}/draft", category: "USER_FACING_UI", client: "api/workflows.ts#saveWorkflowDraft", ui: "features/workflows/useWorkflowEditorActions.ts" },
  { method: "POST", path: "/api/v1/workflows/definitions/{definition_id}/runs", category: "USER_FACING_UI", client: "api/workflows.ts#startWorkflowRun", ui: "features/workflows/useWorkflowEditorActions.ts" },
  { method: "POST", path: "/api/v1/workflows/resume", category: "MACHINE_ONLY", exemptionReason: "Token/event resume for approval webhooks and integrations; operators use node-scoped resume on the run detail page." },
  { method: "POST", path: "/api/v1/workflows/runs/{run_id}/advance", category: "USER_FACING_UI", client: "api/workflows.ts#advanceWorkflowRun", ui: "pages/WorkflowRunDetailPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/runs/{run_id}/cancel", category: "USER_FACING_UI", client: "api/workflows.ts#cancelWorkflowRun", ui: "pages/WorkflowRunDetailPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/runs/{run_id}/nodes/{node_id}/retry", category: "USER_FACING_UI", client: "api/workflows.ts#retryWorkflowNode", ui: "pages/WorkflowRunDetailPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/runs/{run_id}/retry-from/{node_id}", category: "USER_FACING_UI", client: "api/workflows.ts#retryWorkflowFromNode", ui: "pages/WorkflowRunDetailPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/runs/{run_id}/nodes/{node_id}/resume", category: "USER_FACING_UI", client: "api/workflows.ts#resumeWorkflowNode", ui: "pages/WorkflowRunDetailPage.tsx" },
  { method: "GET", path: "/api/v1/workflows/runs/{run_id}", category: "USER_FACING_UI", client: "api/workflows.ts#getWorkflowRun", ui: "pages/WorkflowRunDetailPage.tsx" },
  { method: "GET", path: "/api/v1/workflows/runs", category: "USER_FACING_UI", client: "api/workflows.ts#listWorkflowRuns", ui: "pages/WorkflowRunsPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/definitions/{definition_id}/publish", category: "USER_FACING_UI", client: "api/workflows.ts#publishWorkflowVersion", ui: "features/workflows/useWorkflowEditorActions.ts" },
  { method: "GET", path: "/api/v1/workflows/definitions/{definition_id}/versions", category: "USER_FACING_UI", client: "api/workflows.ts#listWorkflowVersions", ui: "pages/WorkflowEditorPage.tsx" },
  { method: "GET", path: "/api/v1/workflows/definitions/{definition_id}", category: "USER_FACING_UI", client: "api/workflows.ts#getWorkflowDefinition", ui: "pages/WorkflowEditorPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/definitions", category: "USER_FACING_UI", client: "api/workflows.ts#createWorkflowDefinition", ui: "pages/WorkflowsPage.tsx" },
  { method: "GET", path: "/api/v1/workflows/definitions", category: "USER_FACING_UI", client: "api/workflows.ts#listWorkflowDefinitions", ui: "pages/WorkflowsPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/nodes/{node_type}/validate-config", category: "USER_FACING_UI", client: "api/workflows.ts#validateWorkflowNodeConfig", ui: "features/workflows/WorkflowNodeConfigForm.tsx" },
  { method: "POST", path: "/api/v1/workflows/nodes/{node_type}/test", category: "USER_FACING_UI", client: "api/workflows.ts#testWorkflowNode", ui: "features/workflows/useWorkflowEditorActions.ts" },
  { method: "GET", path: "/api/v1/workflows/nodes/{node_type}", category: "INTENTIONALLY_NO_UI", exemptionReason: "Single node lookup unused; editor uses list catalog." },
  { method: "GET", path: "/api/v1/workflows/nodes", category: "USER_FACING_UI", client: "api/workflows.ts#listWorkflowNodes", ui: "pages/WorkflowEditorPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/validate-graph", category: "USER_FACING_UI", client: "api/workflows.ts#validateWorkflowGraph", ui: "features/workflows/useWorkflowEditorActions.ts" },
  { method: "POST", path: "/api/v1/workflows/simulate-graph", category: "MACHINE_ONLY", exemptionReason: "Design what-if compile; editor uses validate-graph today." },
  { method: "GET", path: "/api/v1/workflows/automations", category: "USER_FACING_UI", client: "api/workflows.ts#listAutomations", ui: "pages/AutomationsPage.tsx" },
  { method: "POST", path: "/api/v1/workflows/automations", category: "USER_FACING_UI", client: "api/workflows.ts#createAutomation", ui: "pages/AutomationsPage.tsx" },
  { method: "GET", path: "/api/v1/workflows/automations/{automation_id}", category: "INTENTIONALLY_NO_UI", exemptionReason: "Automation detail fetch unused; list+patch cover Phase 13 UI." },
  { method: "PATCH", path: "/api/v1/workflows/automations/{automation_id}", category: "USER_FACING_UI", client: "api/workflows.ts#updateAutomation", ui: "pages/AutomationsPage.tsx" },
  { method: "GET", path: "/api/v1/workflows/brands", category: "USER_FACING_UI", client: "api/workflows.ts#listWorkflowBrands", ui: "pages/AutomationsPage.tsx" },
  { method: "GET", path: "/api/v1/users/directory", category: "INTENTIONALLY_NO_UI", exemptionReason: "Tenant user directory for future assignee pickers; no current product screen." },
  { method: "GET", path: "/api/v1/users/me", category: "USER_FACING_UI", client: "api/users.ts#getMyProfile", ui: "features/settings/AccountTab.tsx" },
  { method: "PATCH", path: "/api/v1/users/me", category: "USER_FACING_UI", client: "api/users.ts#updateMyProfile", ui: "features/settings/AccountTab.tsx" },
  { method: "PATCH", path: "/api/v1/users/me/password", category: "USER_FACING_UI", client: "api/users.ts#changeMyPassword", ui: "features/settings/AccountTab.tsx" },
  { method: "GET", path: "/api/v1/users/me/sessions", category: "USER_FACING_UI", client: "api/users.ts#listMySessions", ui: "features/settings/AccountTab.tsx" },
  { method: "DELETE", path: "/api/v1/users/me/sessions/{session_id}", category: "USER_FACING_UI", client: "api/users.ts#revokeMySession", ui: "features/settings/AccountTab.tsx" },
];
