"""initial_schema

Revision ID: e376ce15cbe2
Revises: 
Create Date: 2026-04-05 13:42:06.656460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e376ce15cbe2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions'))
    )
    op.create_index('ix_permissions_code', 'permissions', ['code'], unique=True)
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('plan_tier', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants'))
    )
    op.create_index('ix_tenants_slug', 'tenants', ['slug'], unique=True)
    op.create_table('brand_profiles',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('niche', sa.String(length=128), nullable=False),
    sa.Column('tone', sa.String(length=128), nullable=False),
    sa.Column('audience', sa.Text(), nullable=False),
    sa.Column('voice_notes', sa.Text(), nullable=True),
    sa.Column('preferred_platforms', sa.JSON(), nullable=False),
    sa.Column('default_cta', sa.Text(), nullable=True),
    sa.Column('hashtags_strategy', sa.String(length=128), nullable=False),
    sa.Column('risk_tolerance', sa.String(length=32), nullable=False),
    sa.Column('require_whatsapp_approval', sa.Boolean(), nullable=False),
    sa.Column('guardrails', sa.JSON(), nullable=False),
    sa.Column('visual_style', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_brand_profiles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brand_profiles'))
    )
    op.create_index('ix_brand_profiles_tenant_id', 'brand_profiles', ['tenant_id'], unique=False)
    op.create_table('roles',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('permission_codes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_roles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('tenant_id', 'slug', name='uq_roles_tenant_id_slug')
    )
    op.create_index('ix_roles_tenant_id', 'roles', ['tenant_id'], unique=False)
    op.create_table('social_accounts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('handle', sa.String(length=255), nullable=True),
    sa.Column('account_external_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('capability_flags', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_social_accounts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_accounts')),
    sa.UniqueConstraint('tenant_id', 'platform', 'account_external_id', name='uq_social_accounts_tenant_id_platform_account_external_id')
    )
    op.create_index('ix_social_accounts_tenant_id_platform', 'social_accounts', ['tenant_id', 'platform'], unique=False)
    op.create_table('sources',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('parser_type', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('polling_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('robots_respected', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('circuit_state', sa.String(length=32), nullable=False),
    sa.Column('negative_cache_until', sa.DateTime(), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('stale_cache_ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_sources_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('tenant_id', 'name', name='uq_sources_tenant_id_name')
    )
    op.create_index('ix_sources_tenant_id_active', 'sources', ['tenant_id', 'active'], unique=False)
    op.create_table('task_executions',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('queue_name', sa.String(length=64), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=True),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('cancellable', sa.Boolean(), nullable=False),
    sa.Column('cancellation_requested', sa.Boolean(), nullable=False),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_task_executions_tenant_id_tenants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_executions'))
    )
    op.create_index('ix_task_executions_queue_name_status', 'task_executions', ['queue_name', 'status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('default_tenant_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_tenant_id'], ['tenants.id'], name=op.f('fk_users_default_tenant_id_tenants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_default_tenant_id'), 'users', ['default_tenant_id'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('webhooks_inbox',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_webhooks_inbox_tenant_id_tenants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhooks_inbox')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_webhooks_inbox_dedupe_key'))
    )
    op.create_index('ix_webhooks_inbox_provider_received_at', 'webhooks_inbox', ['provider', 'received_at'], unique=False)
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.Uuid(), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('entity_type', sa.String(length=128), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_logs_actor_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_tenant_id_created_at', 'audit_logs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('refresh_sessions',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_sessions'))
    )
    op.create_index('ix_refresh_sessions_token_hash', 'refresh_sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_sessions_user_id'), 'refresh_sessions', ['user_id'], unique=False)
    op.create_table('social_account_tokens',
    sa.Column('social_account_id', sa.Uuid(), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=False),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_refreshed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], name=op.f('fk_social_account_tokens_social_account_id_social_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_account_tokens'))
    )
    op.create_index('ix_social_account_tokens_social_account_id', 'social_account_tokens', ['social_account_id'], unique=False)
    op.create_table('source_fetch_runs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('articles_found', sa.Integer(), nullable=False),
    sa.Column('new_articles', sa.Integer(), nullable=False),
    sa.Column('response_cache_hit', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_fetch_runs_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_source_fetch_runs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_fetch_runs'))
    )
    op.create_index('ix_source_fetch_runs_source_id_created_at', 'source_fetch_runs', ['source_id', 'created_at'], unique=False)
    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=True),
    sa.Column('membership_status', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_tenant_users_role_id_roles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_tenant_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_tenant_users_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenant_users')),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tenant_users_tenant_id_user_id')
    )
    op.create_index('ix_tenant_users_user_id', 'tenant_users', ['user_id'], unique=False)
    op.create_table('raw_articles',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('fetch_run_id', sa.Uuid(), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('content_hash', sa.String(length=128), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['source_fetch_runs.id'], name=op.f('fk_raw_articles_fetch_run_id_source_fetch_runs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_articles_source_id_sources'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_raw_articles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_articles')),
    sa.UniqueConstraint('tenant_id', 'content_hash', name='uq_raw_articles_tenant_id_content_hash')
    )
    op.create_index('ix_raw_articles_source_id_canonical_url', 'raw_articles', ['source_id', 'canonical_url'], unique=False)
    op.create_index('ix_raw_articles_tenant_id_published_at', 'raw_articles', ['tenant_id', 'published_at'], unique=False)
    op.create_table('normalized_articles',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('raw_article_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('topic_tags', sa.JSON(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('worthiness_score', sa.Float(), nullable=False),
    sa.Column('explainability', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_article_id'], ['raw_articles.id'], name=op.f('fk_normalized_articles_raw_article_id_raw_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_normalized_articles_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_articles')),
    sa.UniqueConstraint('raw_article_id', name='uq_normalized_articles_raw_article_id')
    )
    op.create_index('ix_normalized_articles_tenant_id_published_at', 'normalized_articles', ['tenant_id', 'published_at'], unique=False)
    op.create_table('story_clusters',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('primary_topic', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('representative_article_id', sa.Uuid(), nullable=True),
    sa.Column('article_count', sa.Integer(), nullable=False),
    sa.Column('trend_direction', sa.String(length=32), nullable=False),
    sa.Column('worthy_for_content', sa.Boolean(), nullable=False),
    sa.Column('risk_level', sa.String(length=32), nullable=False),
    sa.Column('explainability', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['representative_article_id'], ['normalized_articles.id'], name=op.f('fk_story_clusters_representative_article_id_normalized_articles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_story_clusters_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_clusters'))
    )
    op.create_index('ix_story_clusters_tenant_id_created_at', 'story_clusters', ['tenant_id', 'created_at'], unique=False)
    op.create_index('ix_story_clusters_tenant_id_worthy_for_content', 'story_clusters', ['tenant_id', 'worthy_for_content'], unique=False)
    op.create_table('content_plans',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('story_cluster_id', sa.Uuid(), nullable=False),
    sa.Column('brand_profile_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('content_format', sa.String(length=32), nullable=False),
    sa.Column('target_platforms', sa.JSON(), nullable=False),
    sa.Column('tone', sa.String(length=128), nullable=False),
    sa.Column('urgency', sa.String(length=32), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('recommended_cta', sa.Text(), nullable=True),
    sa.Column('hashtags_strategy', sa.String(length=128), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('safe_to_publish', sa.Boolean(), nullable=False),
    sa.Column('policy_trace', sa.JSON(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_profile_id'], ['brand_profiles.id'], name=op.f('fk_content_plans_brand_profile_id_brand_profiles'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_cluster_id'], ['story_clusters.id'], name=op.f('fk_content_plans_story_cluster_id_story_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_content_plans_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_plans'))
    )
    op.create_index('ix_content_plans_story_cluster_id', 'content_plans', ['story_cluster_id'], unique=False)
    op.create_index('ix_content_plans_tenant_id_created_at', 'content_plans', ['tenant_id', 'created_at'], unique=False)
    op.create_table('story_cluster_articles',
    sa.Column('story_cluster_id', sa.Uuid(), nullable=False),
    sa.Column('normalized_article_id', sa.Uuid(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['normalized_article_id'], ['normalized_articles.id'], name=op.f('fk_story_cluster_articles_normalized_article_id_normalized_articles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['story_cluster_id'], ['story_clusters.id'], name=op.f('fk_story_cluster_articles_story_cluster_id_story_clusters'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_story_cluster_articles')),
    sa.UniqueConstraint('story_cluster_id', 'normalized_article_id', name='uq_sca_cluster_article')
    )
    op.create_table('trend_scores',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('story_cluster_id', sa.Uuid(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=False),
    sa.Column('credibility_score', sa.Float(), nullable=False),
    sa.Column('momentum_score', sa.Float(), nullable=False),
    sa.Column('worthiness_score', sa.Float(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['story_cluster_id'], ['story_clusters.id'], name=op.f('fk_trend_scores_story_cluster_id_story_clusters'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_trend_scores_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trend_scores'))
    )
    op.create_index('ix_trend_scores_story_cluster_id_created_at', 'trend_scores', ['story_cluster_id', 'created_at'], unique=False)
    op.create_table('content_jobs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_plan_id', sa.Uuid(), nullable=False),
    sa.Column('revision_of_job_id', sa.Uuid(), nullable=True),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('grounding_bundle', sa.JSON(), nullable=False),
    sa.Column('provider_metadata', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_plan_id'], ['content_plans.id'], name=op.f('fk_content_jobs_content_plan_id_content_plans'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_of_job_id'], ['content_jobs.id'], name=op.f('fk_content_jobs_revision_of_job_id_content_jobs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_content_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_jobs'))
    )
    op.create_index('ix_content_jobs_content_plan_id', 'content_jobs', ['content_plan_id'], unique=False)
    op.create_index('ix_content_jobs_tenant_id_created_at', 'content_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('content_revisions',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_job_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('source_channel', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('diff_summary', sa.Text(), nullable=True),
    sa.Column('revision_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_job_id'], ['content_jobs.id'], name=op.f('fk_content_revisions_content_job_id_content_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_content_revisions_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_content_revisions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_content_revisions'))
    )
    op.create_index('ix_content_revisions_content_job_id', 'content_revisions', ['content_job_id'], unique=False)
    op.create_table('generated_assets',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_job_id', sa.Uuid(), nullable=False),
    sa.Column('asset_type', sa.String(length=64), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=True),
    sa.Column('variant_label', sa.String(length=16), nullable=True),
    sa.Column('storage_key', sa.String(length=1024), nullable=True),
    sa.Column('public_url', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('source_trace', sa.JSON(), nullable=False),
    sa.Column('text_content', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_job_id'], ['content_jobs.id'], name=op.f('fk_generated_assets_content_job_id_content_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_generated_assets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_assets'))
    )
    op.create_index('ix_generated_assets_content_job_id', 'generated_assets', ['content_job_id'], unique=False)
    op.create_index('ix_generated_assets_tenant_id_asset_type', 'generated_assets', ['tenant_id', 'asset_type'], unique=False)
    op.create_table('approval_requests',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_job_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('recipient', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('requested_at', sa.DateTime(), nullable=True),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('revision_count', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_user_id'], ['users.id'], name=op.f('fk_approval_requests_approved_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_job_id'], ['content_jobs.id'], name=op.f('fk_approval_requests_content_job_id_content_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_approval_requests_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests'))
    )
    op.create_index('ix_approval_requests_tenant_id_status', 'approval_requests', ['tenant_id', 'status'], unique=False)
    op.create_table('approval_messages',
    sa.Column('approval_request_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('parsed_intent', sa.String(length=32), nullable=False),
    sa.Column('intent_confidence', sa.Float(), nullable=False),
    sa.Column('user_feedback', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_approval_messages_approval_request_id_approval_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_messages'))
    )
    op.create_index('ix_approval_messages_approval_request_id', 'approval_messages', ['approval_request_id'], unique=False)
    op.create_table('publishing_jobs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('content_job_id', sa.Uuid(), nullable=False),
    sa.Column('social_account_id', sa.Uuid(), nullable=True),
    sa.Column('approval_request_id', sa.Uuid(), nullable=True),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('provider_payload', sa.JSON(), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('external_post_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approval_requests.id'], name=op.f('fk_publishing_jobs_approval_request_id_approval_requests'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['content_job_id'], ['content_jobs.id'], name=op.f('fk_publishing_jobs_content_job_id_content_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], name=op.f('fk_publishing_jobs_social_account_id_social_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_publishing_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_publishing_jobs')),
    sa.UniqueConstraint('idempotency_key', name='uq_publishing_jobs_idempotency_key')
    )
    op.create_index('ix_publishing_jobs_tenant_id_status', 'publishing_jobs', ['tenant_id', 'status'], unique=False)
    op.create_table('published_posts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('social_account_id', sa.Uuid(), nullable=True),
    sa.Column('publishing_job_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('post_type', sa.String(length=32), nullable=False),
    sa.Column('external_post_id', sa.String(length=255), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('analytics_sync_state', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['publishing_job_id'], ['publishing_jobs.id'], name=op.f('fk_published_posts_publishing_job_id_publishing_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['social_account_id'], ['social_accounts.id'], name=op.f('fk_published_posts_social_account_id_social_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_published_posts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_published_posts'))
    )
    op.create_index('ix_published_posts_tenant_id_platform', 'published_posts', ['tenant_id', 'platform'], unique=False)
    op.create_table('analytics_snapshots',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('published_post_id', sa.Uuid(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('topic', sa.String(length=128), nullable=True),
    sa.Column('content_format', sa.String(length=32), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('watch_time_seconds', sa.Integer(), nullable=False),
    sa.Column('ctr', sa.Float(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['published_post_id'], ['published_posts.id'], name=op.f('fk_analytics_snapshots_published_post_id_published_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_analytics_snapshots_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_snapshots')),
    sa.UniqueConstraint('published_post_id', 'snapshot_date', name='uq_analytics_snapshots_published_post_id_snapshot_date')
    )
    op.create_index('ix_analytics_snapshots_tenant_id_snapshot_date', 'analytics_snapshots', ['tenant_id', 'snapshot_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_analytics_snapshots_tenant_id_snapshot_date', table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_index('ix_published_posts_tenant_id_platform', table_name='published_posts')
    op.drop_table('published_posts')
    op.drop_index('ix_publishing_jobs_tenant_id_status', table_name='publishing_jobs')
    op.drop_table('publishing_jobs')
    op.drop_index('ix_approval_messages_approval_request_id', table_name='approval_messages')
    op.drop_table('approval_messages')
    op.drop_index('ix_approval_requests_tenant_id_status', table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index('ix_generated_assets_tenant_id_asset_type', table_name='generated_assets')
    op.drop_index('ix_generated_assets_content_job_id', table_name='generated_assets')
    op.drop_table('generated_assets')
    op.drop_index('ix_content_revisions_content_job_id', table_name='content_revisions')
    op.drop_table('content_revisions')
    op.drop_index('ix_content_jobs_tenant_id_created_at', table_name='content_jobs')
    op.drop_index('ix_content_jobs_content_plan_id', table_name='content_jobs')
    op.drop_table('content_jobs')
    op.drop_index('ix_trend_scores_story_cluster_id_created_at', table_name='trend_scores')
    op.drop_table('trend_scores')
    op.drop_table('story_cluster_articles')
    op.drop_index('ix_content_plans_tenant_id_created_at', table_name='content_plans')
    op.drop_index('ix_content_plans_story_cluster_id', table_name='content_plans')
    op.drop_table('content_plans')
    op.drop_index('ix_story_clusters_tenant_id_worthy_for_content', table_name='story_clusters')
    op.drop_index('ix_story_clusters_tenant_id_created_at', table_name='story_clusters')
    op.drop_table('story_clusters')
    op.drop_index('ix_normalized_articles_tenant_id_published_at', table_name='normalized_articles')
    op.drop_table('normalized_articles')
    op.drop_index('ix_raw_articles_tenant_id_published_at', table_name='raw_articles')
    op.drop_index('ix_raw_articles_source_id_canonical_url', table_name='raw_articles')
    op.drop_table('raw_articles')
    op.drop_index('ix_tenant_users_user_id', table_name='tenant_users')
    op.drop_table('tenant_users')
    op.drop_index('ix_source_fetch_runs_source_id_created_at', table_name='source_fetch_runs')
    op.drop_table('source_fetch_runs')
    op.drop_index('ix_social_account_tokens_social_account_id', table_name='social_account_tokens')
    op.drop_table('social_account_tokens')
    op.drop_index(op.f('ix_refresh_sessions_user_id'), table_name='refresh_sessions')
    op.drop_index('ix_refresh_sessions_token_hash', table_name='refresh_sessions')
    op.drop_table('refresh_sessions')
    op.drop_index('ix_audit_logs_tenant_id_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_webhooks_inbox_provider_received_at', table_name='webhooks_inbox')
    op.drop_table('webhooks_inbox')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index(op.f('ix_users_default_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_task_executions_queue_name_status', table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index('ix_sources_tenant_id_active', table_name='sources')
    op.drop_table('sources')
    op.drop_index('ix_social_accounts_tenant_id_platform', table_name='social_accounts')
    op.drop_table('social_accounts')
    op.drop_index('ix_roles_tenant_id', table_name='roles')
    op.drop_table('roles')
    op.drop_index('ix_brand_profiles_tenant_id', table_name='brand_profiles')
    op.drop_table('brand_profiles')
    op.drop_index('ix_tenants_slug', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_permissions_code', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
